//! `ahu explain` — the architecture overview built into the CLI.
//!
//! The overview exists so the model ahu works to is available where people
//! actually are. It is written once as a small document tree and rendered two
//! ways, so the terminal text and the Markdown can never drift apart.
//!
//! The Markdown form carries the diagrams as ```` ```mermaid ```` fences, which
//! render unchanged on GitHub and in cmux's own Markdown viewer.

use std::path::{Path, PathBuf};

use crate::util::{Error, Result};

pub fn markdown() -> String {
    let mut out = format!(
        "# ahu {} — architecture overview\n",
        env!("CARGO_PKG_VERSION")
    );
    let content = include_str!("../.agents/skills/ahu-architecture/SKILL.md");

    // strip frontmatter
    let body = if let Some(stripped) = content.strip_prefix("---\n") {
        if let Some(end) = stripped.find("\n---\n") {
            &stripped[end + 5..]
        } else {
            content
        }
    } else {
        content
    };
    out.push_str(body.trim());
    out.push_str("\n\n## Compatibility\n\n");

    out.push_str(&format!(
        "Compatibility catalog {} ships with this build and is fixed by project\n\
         configuration, so installing a newer ahu cannot silently change which model your\n\
         project selects.\n\n",
        crate::catalog::CATALOG_VERSION
    ));

    out.push_str("| harness | ahu adapter | verified against |\n");
    out.push_str("| --- | --- | --- |\n");
    for harness in crate::catalog::HARNESSES {
        let adapter = if harness.adapter_available {
            "available"
        } else {
            "unavailable"
        };
        let verified = if harness.verified_versions.is_empty() {
            "not verified".to_string()
        } else {
            harness.verified_versions.to_string()
        };
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            harness.id, adapter, verified
        ));
    }

    out.push_str(
        "\n---\n\nGenerated by `ahu explain --markdown`. Run `ahu help` for commands, and\n\
         `ahu doctor` for this machine.\n",
    );

    out
}

pub fn overview() -> String {
    let mut out = format!(
        "ahu {} — architecture overview\n{}\n",
        env!("CARGO_PKG_VERSION"),
        "=".repeat(46)
    );
    let content = include_str!("../.agents/skills/ahu-architecture/SKILL.md");
    let body = if let Some(stripped) = content.strip_prefix("---\n") {
        if let Some(end) = stripped.find("\n---\n") {
            &stripped[end + 5..]
        } else {
            content
        }
    } else {
        content
    };

    let mut in_mermaid = false;
    for line in body.trim().lines() {
        if let Some(title) = line.strip_prefix("## ") {
            out.push_str(&format!("\n{}\n{}\n", title, "-".repeat(title.len())));
        } else if line.starts_with("```mermaid") {
            in_mermaid = true;
            out.push_str("```mermaid\n");
        } else if in_mermaid && line.starts_with("```") {
            in_mermaid = false;
            out.push_str("```\n\n");
        } else if in_mermaid {
            out.push_str(line);
            out.push('\n');
        } else if line.starts_with("> **") {
            out.push_str("  !! ");
            out.push_str(&line[4..].replace("**", ""));
            out.push('\n');
        } else if line.starts_with("> ") {
            out.push_str("     ");
            out.push_str(&line[2..].replace("**", ""));
            out.push('\n');
        } else if line.starts_with("- ") {
            out.push_str("  - ");
            out.push_str(&line[2..].replace("**", ""));
            out.push('\n');
        } else {
            out.push_str(&line.replace("**", ""));
            out.push('\n');
        }
    }

    // trim multiple blank lines before the section
    while out.ends_with("\n\n") {
        out.pop();
    }

    out.push_str("\n\nCompatibility\n-------------\n");
    out.push_str(&format!(
        "Compatibility catalog {} ships with this build and is fixed by project\n\
         configuration, so installing a newer ahu cannot silently change which model your\n\
         project selects.\n\n",
        crate::catalog::CATALOG_VERSION
    ));

    for harness in crate::catalog::HARNESSES {
        let adapter = if harness.adapter_available {
            "available"
        } else {
            "unavailable"
        };
        let verified = if harness.verified_versions.is_empty() {
            "not verified".to_string()
        } else {
            harness.verified_versions.to_string()
        };
        out.push_str(&format!(
            "  {:<14} {:<12} {}\n",
            harness.id, adapter, verified
        ));
    }
    out.push('\n');

    out.push_str(
        "Run `ahu explain --markdown` for the same document as Markdown, `--mermaid` for the\n\
         diagrams alone, or `--open` to render it in cmux's Markdown viewer.\n\
         Run `ahu help` for commands, and `ahu doctor` for this machine.\n",
    );
    out
}

pub fn mermaid_only() -> String {
    let mut out = String::from("# ahu architecture\n");
    let content = include_str!("../.agents/skills/ahu-architecture/SKILL.md");
    let mut in_mermaid = false;
    let mut last_header = "";
    for line in content.lines() {
        if line.starts_with("## ") {
            last_header = &line[3..];
        } else if line.starts_with("```mermaid") {
            in_mermaid = true;
            out.push_str(&format!("\n## {}\n\n```mermaid\n", last_header));
        } else if in_mermaid && line.starts_with("```") {
            in_mermaid = false;
            out.push_str("```\n");
        } else if in_mermaid {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

pub fn document_path() -> Result<PathBuf> {
    Ok(crate::state::root()?.join("docs/architecture.md"))
}

pub fn write_document() -> Result<PathBuf> {
    let path = document_path()?;
    crate::state::write_private_file(&path, markdown().as_bytes())
        .map_err(|e| Error::new(format!("cannot write {}: {e}", path.display())))?;
    Ok(path)
}

pub fn open_in_cmux(path: &Path, focus: bool) -> Result<String> {
    let client = crate::cmux::Cmux::discover()?;
    client.open_markdown(path, focus)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_markdown_renders() {
        let md = markdown();
        assert!(md.contains("# ahu"));
        assert!(md.contains("architecture overview"));
        assert!(md.contains("Compatibility catalog"));
    }

    #[test]
    fn test_overview_renders() {
        let ov = overview();
        assert!(ov.contains("ahu"));
        assert!(ov.contains("architecture overview"));
        assert!(ov.contains("Compatibility catalog"));
    }

    #[test]
    fn test_mermaid_renders() {
        let mo = mermaid_only();
        assert!(mo.contains("```mermaid"));
        assert!(mo.contains("flowchart TD"));
    }
}
